name: Model Retraining and Docker Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn matplotlib seaborn

    - name: Run MLflow Project (Model Retraining)
      run: |
        mlflow run MLProject --env-manager=local


    - name: Locate and Copy Trained Model
      run: |
        echo "=== Current Directory Structure ==="
        find . -maxdepth 4 -not -path '*/.*'
        
        # Cari direktori model yang dihasilkan di mlruns (yang berisi file MLmodel)
        MODEL_PATH=$(find . -name "MLmodel" -exec dirname {} \; | grep "mlruns" | head -n 1)
        echo "Trained model found at: $MODEL_PATH"
        if [ -z "$MODEL_PATH" ]; then
          echo "ERROR: Model path not found in mlruns!"
          exit 1
        fi
        mkdir -p MLProject/model_dir
        cp -r "$MODEL_PATH"/* MLProject/model_dir/
        ls -la MLProject/model_dir/



    - name: Upload Trained Model as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: heart-disease-random-forest-model
        path: MLProject/model_dir/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./MLProject
        file: ./MLProject/Dockerfile
        push: true
        tags: lasercl/heart-disease-model:latest
